# 6 NumPy Coding Problems

In [1]:
import numpy as np

In [ ]:
#1 Create a null vector of size 10 but the fifth value which is 1.

In [2]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#2. Create a vector with values ranging from 10 to 49

In [5]:
b=np.arange(10,50)

In [6]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
c= np.arange(0,9).reshape(3, 3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
d = [1,2,0,0,4,0]
d_new = []
for i in range(len(d)):
    if d[i]!=0:
        d_new.append(i)
print(d_new)

[0, 1, 4]


In [24]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
e = np.random.random((10,10))

In [20]:
e

array([[1.07035428e-01, 3.02556495e-01, 8.10471637e-01, 6.96566019e-01,
        8.96373917e-02, 3.69580329e-01, 1.49544218e-01, 9.75591675e-01,
        3.81622948e-01, 2.45841779e-01],
       [2.81132570e-01, 2.98420005e-02, 4.88116553e-01, 7.87367861e-01,
        4.29896466e-01, 5.99367984e-04, 4.40720332e-01, 3.76800150e-01,
        2.86589198e-01, 7.54875183e-01],
       [5.72945849e-01, 1.66102930e-01, 4.11050213e-01, 7.10059362e-01,
        5.59537491e-01, 2.75044991e-01, 4.22226309e-01, 3.83787496e-01,
        6.80737870e-01, 2.34666011e-01],
       [7.25387164e-01, 5.31328335e-01, 7.88167165e-01, 1.03209531e-01,
        8.11149272e-01, 9.65625365e-01, 3.62123988e-01, 5.55440507e-01,
        9.90403100e-01, 3.08599509e-01],
       [6.84134770e-01, 1.10795193e-01, 9.32057908e-02, 1.95397949e-01,
        2.17017819e-01, 3.66837180e-01, 7.91474715e-01, 6.10628249e-02,
        2.25075057e-01, 3.03037074e-01],
       [9.38493752e-01, 1.59876769e-01, 7.56349820e-01, 8.40192224e-01,
   

In [21]:
e.max()

0.9904031003319068

In [22]:
e.min()

0.0005993679838223187

In [25]:
#6. Create a random vector of size 30 and find the mean value.
f=np.random.rand(30)

In [26]:
f

array([0.54835513, 0.75499868, 0.89867202, 0.23467964, 0.66642482,
       0.39271972, 0.96075876, 0.1355262 , 0.15461663, 0.44695071,
       0.39654132, 0.15211726, 0.10889099, 0.34195755, 0.05909095,
       0.81459679, 0.75033883, 0.18141679, 0.01979132, 0.19342987,
       0.64923977, 0.5310329 , 0.97375507, 0.80733486, 0.28894428,
       0.00705169, 0.52188165, 0.03629181, 0.13514965, 0.26866028])

In [27]:
f.mean()

0.41437386441748536